In [2]:
import numpy as pn

In [5]:
pn.array([0,1,2,3,4,5])

array([0, 1, 2, 3, 4, 5])

In [10]:
arr = pn.array(["diwakaran"], dtype='U9')


In [14]:
range=pn.arange(0,15,3)

In [15]:
range

array([ 0,  3,  6,  9, 12])

In [17]:
arr=pn.linspace(0, 1, 5)
arr


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#how to find step value
#step = (end - start) / (num - 1)
