In [2]:
import numpy as pn

In [5]:
pn.array([0,1,2,3,4,5])

array([0, 1, 2, 3, 4, 5])

In [10]:
arr = pn.array(["diwakaran"], dtype='U9')


In [14]:
range=pn.arange(0,15,3)

In [15]:
range

array([ 0,  3,  6,  9, 12])

In [17]:
arr=pn.linspace(0, 1, 5)
arr


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#how to find step value
#step = (end - start) / (num - 1)


In [18]:
arr=pn.linspace(0, 1, 10)
arr


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
pn.logspace(1, 3 ,3)

array([  10.,  100., 1000.])

np.zeros->array full of zeros

In [27]:
array=pn.zeros(7)
array

array([0., 0., 0., 0., 0., 0., 0.])

matrix structure


In [29]:
arr=pn.zeros([2,7])
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [30]:
arr=pn.zeros([2,3,5,6,8])
arr

array([[[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

        

In [32]:
arr=pn.ones([2,1])
arr

array([[1.],
       [1.]])

In [33]:
arr=pn.ones([4,2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])